### ISSUE TITLE
챕터 #11: 불쾌한 컴포넌트 리렌더링

### ISSUE THREAD

**Issue by pinkrabbit412** [pinkrabbit412/ReactStudy#1]
# 챕터 #11: 불쾌한 컴포넌트 리렌더링

## 🎯 대상 챕터
[Chapter #11 - Component Performance Optimization](https://github.com/pinkrabbit412/ReactStudy/tree/main/11.%20Component%20Performance%20Optimization)
<br />

## ⁉️ 발생 문제
교재 제공 코드대로 `TodoListItem.scss` 파일을 작성하면, `react-virtualized` 패키지에 의해 스크롤 할 때마다 요소의 표시 순서가 홀수번째에서 짝수번째로 변하거나, 그 반대로 변함. 이 때, `&:nth-child(even)` 에 의해 `background-color`도 계속 같이 바뀌며, 사용자에게 **마치 렌더링 오류가 발생하는 것 같은 불쾌한 느낌**을 심어주는 현상 발견
<br />

## ✨ 생각한 해결 방안
`classname` 패키지를 사용해,
각 요소에 사용되는 객체의 `index` 값에 따라 절대적인 `background-color` 값 부여하기

**Comment by pinkrabbit412** [comment]
# 챕터 #11: 불쾌한 컴포넌트 리렌더링

## ❔ 해결 여부
**✅ 해결하였음.**
<br />

## ✨ 해결 방안이 적용된 소스코드
공간 문제로, 수정한 부분만 작성하였음.
### ./TodoListItem.js
```Javascript
	const { index, text, isTodoChecked } = todo;
	return (
		<div className="TodoListItem-Virtualized" style={style}>
			// <div className="TodoListItem"> 이 줄을 아래 줄과 같이 변경함.
			<div className={ cn( "TodoListItem", { pink: !(index % 2) } ) }>
				<div
					className={cn("checkBox", { isTodoChecked })}
					onClick={() => whenTodoCheckboxClicked(index)}
```

### ./TodoListItem.js
```scss
.TodoListItem {
    display: flex;
    padding: 1rem;
    /* 불필요한 소스코드를 주석처리하였으며, 아래의 &.pink {} 로 대체함
    &:nth-child(even) {
        background-color: #ffecf5;
    } */
    &.pink {
        background-color: #ffecf5;
    }
    .checkBox {
        // 체크박스 아이콘입니다.
        cursor: pointer;
```
